### ISSUE TITLE
Preserve folder structure

### ISSUE THREAD

**Issue by dimkk** [s-KaiNet/spsave#1]
Hello, tried your util - amazing.

But this one thing which made me sad - flat file structure of my dist folder of gulp-angular yeoman generator in destination folder in SharePoint(

I will try to PR asap, to fill the gap.

Thanks for sharing!

**Comment by s-KaiNet** [comment]
Hi, thank you!
Could you please explain in more details what is the issue? I'm afraid that I don't understand it clearly..
