### ISSUE TITLE
Support for federated identity authentication?

### ISSUE THREAD

**Issue by lifan0127** [s-KaiNet/spsave#16]
Hello @s-KaiNet, will spsave support O365 federated identity authentication?

https://technet.microsoft.com/en-us/library/office-365-user-account-management.aspx

**Comment by s-KaiNet** [comment]
Hi @lifan0127 
No, currently it uses SAML user authentication.

**Comment by lifan0127** [comment]
Thanks for your quick response! It seems federated identity is widely used by large corporations for O365. Do you have any plan to support it in the future, or any suggestion on how I can implement it myself?

**Comment by s-KaiNet** [comment]
I don't have plans to support it and I don't have an experience implementing federated identity for O365. Sorry, can't help.
