### ISSUE TITLE
Aspx pages

### ISSUE THREAD

**Issue by simkessy** [s-KaiNet/spsave#17]
I tried to use this to move and ASPX page and I got an access denied error, So I tried changing it to an HTML page and that worked fine. Any ideas?

**Comment by s-KaiNet** [comment]
For me it looks like permissions problem. Make sure your user has " Add and Customize Pages" permission level.  
Also you can check that `.aspx` is not under blocked file types.

**Comment by simkessy** [comment]
It was. Everything works perfectly now, thanks!
