### ISSUE TITLE
how to ignore folder and files?

### ISSUE THREAD

**Issue by mauricionr** [s-KaiNet/spsave#21]
how to ignore folder and files?

like 
node_modules
.git
....

**Comment by s-KaiNet** [comment]
You need to use glob file content option with negated pattern. Actually `spsave` pass everything you specify in glob to [globby](https://github.com/sindresorhus/globby) module.  

``` javascript
spsave({
  siteUrl: '[sp url]',  username: '[username]', password: '[password]',
  glob: ['myapp/**/*.*', '!node_modules'],
  base: 'myapp',
  folder: 'SiteAssets'
})
```

Code above should upload everything except `node_modules`
