### ISSUE TITLE
How to Stored MetaData for the document in Sharepoint 2013 Online Library

### ISSUE THREAD

**Issue by kaushikmehta012** [s-KaiNet/spsave#27]
Using spsave i am able to upload document in SharePoint online 2013 Document library, Now i want to store some metadata of the document.
Please let me know how we can do this ?

**Comment by s-KaiNet** [comment]
Please, take a look at the [Recipes](https://github.com/s-KaiNet/spsave/blob/master/docs/Recipes.md) page [here](https://github.com/s-KaiNet/spsave/blob/master/docs/Recipes.md#save-file-using-its-name-and-content-update-metadata-for-the-file) and [here](https://github.com/s-KaiNet/spsave/blob/master/docs/Recipes.md#upload-search-display-template-to-master-page-gallery)

**Comment by s-KaiNet** [comment]
@kaushikmehta012 
 Did you manage to solve your issue?

**Comment by kaushikmehta012** [comment]
Thank you, Now able to save metadata.
