### ISSUE TITLE
unable to set page layout associate content type

### ISSUE THREAD

**Issue by tom-daly** [s-KaiNet/spsave#28]
I was trying to deploy a page layout and i need to set the property of the associated content type.
https://www.screencast.com/t/E7S5emQe

I went looking at the object for the field and I don't see it. I'm wondering if you have any recommendations for setting that field value.

```
Object {odata.metadata: "https://bandrdev.sharepoint.com/_api/$metadata#SP.…ta__x005f_catalogs_x002f_masterpageItems/@Element", odata.type: "SP.Data.OData__x005f_catalogs_x002f_masterpageItem", odata.id: "da0edb91-a388-4f42-b359-2a273a333d11", odata.etag: ""10"", odata.editLink: "Web/Lists(guid'6ce3f20b-1de4-430e-b5f0-effe118aa75e')/Items(3498)"…}
AnonymousCacheProfileId
:
null
AuthenticatedCacheProfileId
:
null
AuthorId
:
11
CheckoutUserId
:
null
CompatibleManagedProperties
:
null
CompatibleSearchDataTypes
:
null
ContentTypeId
:
"0x01010007FF3E057FA8AB4AA42FCB67B453FFC100E214EEE741181F4E9F7ACC43278EE81100B1A4769B4017DF41BF9143357A5A55E1"
CrawlerXSLFile
:
null
Created
:
"2017-04-25T19:16:26Z"
DefaultCssFile
:
null
DisplayTemplateJSIconUrl
:
null
DisplayTemplateJSTargetControlType
:
null
DisplayTemplateJSTargetListTemplate
:
null
DisplayTemplateJSTargetScope
:
null
DisplayTemplateJSTemplateHidden
:
null
DisplayTemplateJSTemplateType
:
null
DisplayTemplateLevel
:
null
EditorId
:
11
FileSystemObjectType
:
0
GUID
:
"1eea1b55-51d7-4367-a86a-da24f7434fad"
HtmlDesignAssociated
:
null
HtmlDesignPreviewUrl
:
null
HtmlDesignStatusAndPreview
:
null
ID
:
3498
Id
:
3498
ManagedPropertyMapping
:
null
MasterPageDescription
:
null
Modified
:
"2017-04-25T19:56:49Z"
OData__CopySource
:
null
OData__UIVersionString
:
"0.10"
PublishingAssociatedVariations
:
null
PublishingContactId
:
null
PublishingContactStringId
:
null
PublishingHidden
:
false
PublishingPreviewImage
:
null
ServerRedirectedEmbedUri
:
null
ServerRedirectedEmbedUrl
:
""
TargetControlType
:
null
TemplateHidden
:
null
Title
:
"123123213"
UIVersion
:
null
odata.editLink
:
"Web/Lists(guid'6ce3f20b-1de4-430e-b5f0-effe118aa75e')/Items(3498)"
odata.etag
:
""10""
odata.id
:
"da0edb91-a388-4f42-b359-2a273a333d11"
odata.metadata
:
"https://bandrdev.sharepoint.com/_api/$metadata#SP.ListData.OData__x005f_catalogs_x002f_masterpageItems/@Element"
odata.type
:
"SP.Data.OData__x005f_catalogs_x002f_masterpageItem"
```

**Comment by s-KaiNet** [comment]
Hi, 
Have you tried approach demonstrated [here](https://github.com/s-KaiNet/spsave/blob/master/docs/Recipes.md#upload-search-display-template-to-master-page-gallery)?

**Comment by tom-daly** [comment]
Yes - I have exactly the same format as a master page except using different properties. It's stating that the field is not a property. I'll be able to share that in a few hours when I get to the office.

**Comment by tom-daly** [comment]
Didn't realized i closed the issue so re-opening. 

The error is that it's stating the property doesn't exist. I used pnp js to grab they object and look at all it's properties in my first comment and infact it's not there so I understand this error. This is a standard property that I set when I deploy page layouts via a WSP in the xml. 

[14:21:31] spsave: Error occured:
[14:21:31] spsave: 400 - {"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The property 'PublishingAssociatedContentType' does not exist on type 'SP.Data.OData__x005f_catalogs_x002f_masterpageItem'. Make sure to only use property names that are defined by the type."}}}

**Comment by tom-daly** [comment]
Including the block for the files meta data remove publishingassociatedcontenttype works but like i said that is a standard field for a page layout. wondering if it's just a limitation

`        {
            fileName: "demo1.aspx",
            metadata: {
                "__metadata": { type: "SP.Data.OData__x005f_catalogs_x002f_masterpageItem" },
                Title: "123123213",
                ContentTypeId: "0x01010007FF3E057FA8AB4AA42FCB67B453FFC100E214EEE741181F4E9F7ACC43278EE81100BFA7E30933CB224692527479B7C52DC0",
                PublishingAssociatedContentType: {
                    "__metadata": {
                        "type": "Collection(Edm.String)"
                    },
                    "results": [
                        "Page Layout Content Types",
                        "Welcome Page"
                    ]
                }
                
            }
        }`

**Comment by koltyakov** [comment]
Hi Tom,

Do you have Publishing features activated in your Site Collection and Root Web?
Do you deploy layouts to the Root Web? I see that it suppose to be so, but just to be sure. As subwebs do not support layouts in their /_catalogs/masterpage libraries, as far as I know.
Are you able to upload layout .aspx and change its content type to corresponding CT manually?

**Comment by tom-daly** [comment]
yes its publishing site deploying to the root site collection. I just think that it's one property that is not available even though it's important

![image](https://cloud.githubusercontent.com/assets/9259305/25458429/d6801df8-2aa7-11e7-908d-ef50ae878cf6.png)

**Comment by tom-daly** [comment]
I'm using a chrome plugin to get the json properties on the object
https://github.com/tavikukko/Chrome-SP-Editor

and I get the item display the properties that PublishingAssociatedContentType doesn't appear but if I get the item via pnp-js and pnp.sp.web.lists.getByTitle('Master Page Gallery').items.getById(3498).fieldValuesAsHTML you can see the field come back. 

so it does exist on the item however it's possible not set-able?

![image](https://cloud.githubusercontent.com/assets/9259305/25459380/e8e18d48-2aab-11e7-8085-0055f9755f1a.png)

You can see in this that this is a core property for deploying a page layout
http://www.sharepointnutsandbolts.com/2007/04/deploying-master-pages-and-page-layouts.html
![image](https://cloud.githubusercontent.com/assets/9259305/25459562/d91af394-2aac-11e7-8fa6-1ecc474c3869.png)

**Comment by s-KaiNet** [comment]
Looks really really weird.   

Request `_api/Web/Lists/getbytitle('Master Page Gallery')/items(534)/fieldValuesAsHTML` returns `PublishingAssociatedContentType` field value,   

from the other side `_api/Web/Lists/getbytitle('Master Page Gallery')/items(534)?$select=PublishingAssociatedContentType` - error
```
"The field or property 'PublishingAssociatedContentType' does not exist."
```  
Will try to take a look closer.

**Comment by koltyakov** [comment]
Maybe a clue:

```javascript
/sites/site/_api/web/getList('/sites/site/_catalogs/masterpage')/
items(3746)?
  $select=Properties/PublishingAssociatedContentType&
  $expand=Properties
```

`PublishingAssociatedContentType` is inside the `Properties`.

**Comment by s-KaiNet** [comment]
Good point Andrew, but still has no idea how to update this field via rest. Also what I don't understand is why it's under properties, if there is a corresponding field exists.  

It works via CSOM, but simply doesn't work with REST..

**Comment by tom-daly** [comment]
From what I can tell is that you can only use csom to update this.

**Comment by koltyakov** [comment]
Also didn't find a way for updating these item's properties via REST.
Maybe it's not even possible? How about wrapping some raw CSOM requests into Node.js? I could try to extend sp-screwdriver with some methods capable updating item's properties.

UPD: Ooops, forgot this comment unposted here.
I've extended sp-screwdriver (lib for crazy extensions for Node.js to SharePoint communication) with CSOM request package which is capable updating items property bags and `PublishingAssociatedContentType` property in particular.
The example can be seen [here](https://github.com/koltyakov/sp-screwdriver/blob/master/src/api/items.js), usage is [here](https://github.com/koltyakov/sp-screwdriver/blob/master/test/items-test.js). If there is a strong necessity of publishing a layout and changing these properties from one toolchain such approach can be integrated to a gulp task.

**Comment by s-KaiNet** [comment]
wow, great! Thanks Andrew!      

I've tried to set `Sealed` and `Readonly` properties for the field (as per Tomi @tavikukko suggestion in pnp's  gitter), but with no success.  
```
field.ReadOnlyField = false;
field.Sealed = false;
field.Update();
```  
I tend to think this is a bug with REST API, because CSOM works just fine.     
And it seems the only working cross platform solution is the one proposed by Andrew.

**Comment by tom-daly** [comment]
I'll close the issue. That's for looking into it. I'm ok with this answer as I'm working on using pnp to deploy assets and using spsave for fast update of branding, page layouts, display templates.

Just to summarize: spsave is unable to set the property because it's just not settable via REST and you would have to use CSOM, pnp or sp-screwdriver to set that field on the page layout.
