### ISSUE TITLE
'undefined is not a function' at getFolderPathsArray

### ISSUE THREAD

**Issue by SteenMolberg** [s-KaiNet/spsave#3]
I get this error not matter how I specify the src...
I use gulp-spsave and have exactly the same task working in another project that uses the previous version of spsave. Do I have to specify the source differently now?

My task is...

```
gulp.task("deploy-mainsite-siteassets", function () {

    console.log("User: " + config.username);

    return gulp
        .src("./MainSite/SiteAssets/**/*.*")
        .pipe(spsave({
            username: config.username,
            password: config.password,
            siteUrl: confug.url,
            folder: "SiteAssets",
            flatten: false
        }));

});
```

The full error is...

```
[Projectfolder]\node_modules\gulp-spsave\node_modules\spsave\lib\folders.js:107
        if(folder.endsWith("/") && folder !== "/"){
                  ^
TypeError: undefined is not a function
    at getFolderPathsArray ([Projectfolder]\node_modules\gulp-spsave\node_modules\spsave\lib\folders.js:107:12)
    at Object.checkAndCreateIfNotExist ([Projectfolder]\node_modules\gulp-spsave\node_modules\spsave\lib\folders.js:12:21)
    at uploadFile ([Projectfolder]\node_modules\gulp-spsave\node_modules\spsave\lib\spsave.js:151:11)
    at [Projectfolder]\node_modules\gulp-spsave\node_modules\spsave\lib\spsave.js:71:5
    at [Projectfolder]\node_modules\gulp-spsave\node_modules\spsave\lib\spsave.js:100:5
    at finalCallback ([Projectfolder]\node_modules\gulp-spsave\node_modules\spsave\node_modules\httpreq\lib\httpreq.js:111:4)
    at IncomingMessage.<anonymous> ([Projectfolder]\node_modules\gulp-spsave\node_modules\spsave\node_modules\httpreq\lib\httpreq.js:343:5)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by s-KaiNet** [comment]
@SteenMolberg can you please tell me node version (`node -v`) and visual studio version which you are using?

**Comment by SteenMolberg** [comment]
The node version was old v0.12.2 so I tried upgrading. That solved the issue. Thx for very fast response.

**Comment by s-KaiNet** [comment]
JFYI
Besides I pushed 1.0.11 version with custom endsWith implementation, because it's missing in node prior v4.0. Also if you are using visual studio 2015 and task runner it may use it's own node version which may be old. To fix that you need to move `$(PATH)` to the top under Tools -> Options -> External Web Tools: 
![2015-12-16_1209](https://cloud.githubusercontent.com/assets/10658276/11836813/147d0df6-a3ee-11e5-9062-8819644e8fef.png)
In that case Visual Studio will use node from PATH env. variable.

**Comment by SteenMolberg** [comment]
Thx for info…
With this project I was using VS2013 but I’m running my tasks from the command line anyway.

Fra: Sergei Sergeev [mailto:notifications@github.com]
Sendt: 16. december 2015 10:13
Til: s-KaiNet/spsave spsave@noreply.github.com
Cc: Steen Molberg stm@molberg.dk
Emne: Re: [spsave] 'undefined is not a function' at getFolderPathsArray (#3)

JFYI
Besides I pushed 1.0.11 version with custom endsWith implementation, because it's missing in node prior v4.0. Also if you are using visual studio 2015 and task runner it may use it's own node version which may be old. To fix that you need to move $(PATH) to the top under Tools -> Options -> External Web Tools:
[2015-12-16_1209]https://cloud.githubusercontent.com/assets/10658276/11836813/147d0df6-a3ee-11e5-9062-8819644e8fef.png
In that case Visual Studio will use node from PATH env. variable.

**Comment by SteenMolberg** [comment]
Actually Sergei… one question…

Does OnPrem require NTLM or should it work with Kerberos as well?
I have an OnPrem dev farm where I just can’t authenticate…

/Steen

Fra: Sergei Sergeev [mailto:notifications@github.com]
Sendt: 16. december 2015 10:13
Til: s-KaiNet/spsave spsave@noreply.github.com
Cc: Steen Molberg stm@molberg.dk
Emne: Re: [spsave] 'undefined is not a function' at getFolderPathsArray (#3)

JFYI
Besides I pushed 1.0.11 version with custom endsWith implementation, because it's missing in node prior v4.0. Also if you are using visual studio 2015 and task runner it may use it's own node version which may be old. To fix that you need to move $(PATH) to the top under Tools -> Options -> External Web Tools:
[2015-12-16_1209]https://cloud.githubusercontent.com/assets/10658276/11836813/147d0df6-a3ee-11e5-9062-8819644e8fef.png
In that case Visual Studio will use node from PATH env. variable.

**Comment by s-KaiNet** [comment]
Hmm.. didn't test it with Kerberos. Can you see any errors or something?  
If your dev farm have a domain, then you need to provide "domain" option for `spsave`, if there are no domain then try to explicitly provide "workstation" option.  
If that is not helpful, then the only less painful option which I can propose is to extend web application to new url with NTLM authentication only, and use this new web application for `spsave`.

**Comment by SteenMolberg** [comment]
Thx for you answer. I got a real look at it and Kerberos was not enabled as the customer believed. But the had setup formbased auth as well as NTLM. Jeg just disabled the formbased then it worked without problems.

Very nifty tool you created!!! Thx a lot for that.

/steen

Fra: Sergei Sergeev [mailto:notifications@github.com]
Sendt: 16. december 2015 15:18
Til: s-KaiNet/spsave spsave@noreply.github.com
Cc: Steen Molberg stm@molberg.dk
Emne: Re: [spsave] 'undefined is not a function' at getFolderPathsArray (#3)

Hmm.. didn't test it with Kerberos. Can you see any errors or something?

If you dev farm have a domain, then you need to provide "domain" option for spsave, if there are no domain then try to explicitly provide "workstation" option.

If that is not helpful, then the only less painful option which I can propose is to extend web application to new url with NTLM authentication only, and use this new web application for spsave.
