### ISSUE TITLE
Issue with UTF-8 characters

### ISSUE THREAD

**Issue by johannes-z** [s-KaiNet/spsave#30]
I'm using `gulp-spsave`, and encountered with file encoding. 
I've got a simple .html file that is encoded as UTF-8 (also tried UTF-8 with BOM), and umlaut characters, e.g. "Ü" or "Ä". For example, the string `Tatsächlich` becomes `TatsÃ¤chlich` after the file upload. If I copy the file contents manually inside sharepoint designer, the characters render correctly. Is this a problem of spsave or of how sharepoint managed html file uploads?

**Comment by s-KaiNet** [comment]
That might be spsave issue... thanks for reporting, I will take a look

**Comment by s-KaiNet** [comment]
So I've tried to do a quick fix, but without success. Need more time to investigate this issue.     
I've also found, that if you upload that file via regular ribbon -> file -> upload, it also changes encoding.     
So that's not good news actually.    
Are you sure that this file has UTF8?

**Comment by johannes-z** [comment]
Yes, the file is UTF-8 (At least vs code tells me it is). As stated, I also tried it UTF-8 with BOM. Anyway, it seems that if you save the file with `ISO-8859-1` encoding, it works. I'm suspecting that this is a sharepoint problem. Normal ribbon or sharepoint designer upload probably encodes the file differently.

**Comment by koltyakov** [comment]
Oh, bwt, I have a trick for you @johannes-z.
If you place this line somewhere in your .html file it should be rendered correctly in SharePoint CEWP.
```html
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
```

**Comment by s-KaiNet** [comment]
@johannes-z have you tried workaround proposed by Andrew? Do you still have the issue?

**Comment by johannes-z** [comment]
Hm, no that didn't work. Neither did setting `ISO-8859-1`. I guess that this is a sharepoint related problem rather than a spsave issue. Thanks anyway!

**Comment by koltyakov** [comment]
Strange, for me it works all the time.
Sometimes when an HTML with none Latin symbols is uploaded to document libraries for source linking in CEWPs, web part's content is shown in a wrong code page.
But placing meta tag with encoding and making sure, that a document is in UTF-8 makes it force right encoding.
