### ISSUE TITLE
Error when uploading to HTTPS SharePoint server

### ISSUE THREAD

**Issue by Baraks24** [s-KaiNet/spsave#31]
I try to upload a document to a SharePoint site on HTTPS protocol using spsave, but I get the following 
error: 'Cannot read property 'match' of undefined' - it occurs during the NTLM authentication process with the server (inside the node module 'httpntlm').
I sent the following arguments to spsave: 
coreOptions contains 'siteUrl' of the form : 'https://SERVER_NAME/SP_SITE_NAME'
creds contains my username and password,
fileOptions contains 'folder' of the form 'LIBRARY_NAME/FOLDER_NAME', fileName, and fileContent.

When trying to upload a file to a different SharePoint site- that uses HTTP with the same arguments - it works well, and file is uploaded.

**Comment by s-KaiNet** [comment]
A few points to check:   

- Your https site might be extended to some other authentication options and don't use NTLM auth at all  
- Your https site might use NTLM2 which is not supported
- Try to use separate username, password, domain option (username should not contain domain)

**Comment by s-KaiNet** [comment]
Have you managed to resolve your issue?
