### ISSUE TITLE
Promise is neither resolved or rejected when glob pattern matches 0 files

### ISSUE THREAD

**Issue by sg-chrishasz** [s-KaiNet/spsave#33]
Hello @s-KaiNet !

I'm building glob support into [SPGo](https://github.com/readysitego/spgo), and I found that the returned promise object never fulfils when I provide a glob pattern that matches 0 files. I tried using finally() as a workaround, but no luck.

**Example Fix:**
to function spsave in file `SPSave.js`, add the following conditional to the end of the if/else block:
`else{
    reject({title: "0 Files Matched",message:"Glob pattern matched 0 files"}
}`

Let me know if you want me to author a PR, and whether you'd rather me author it directly against the repo, or via fork.

Thanks,
Chris

**Comment by s-KaiNet** [comment]
Hi Chris, thank you for reporting, I will add this rejection by my own, hopefully that's a small change.

**Comment by s-KaiNet** [comment]
Fixed in `3.1.2`, however I've changed rejection object and message a bit, I believe it's fine for you.
