### ISSUE TITLE
Upload files > 250 MB

### ISSUE THREAD

**Issue by sangaloma** [s-KaiNet/spsave#37]
I was trying to upload a relatively big file (600MB) but an error saying that the file is too big to be uploaded. 

Is there any way to do so?

**Comment by s-KaiNet** [comment]
Which SharePoint version do you use?

**Comment by sangaloma** [comment]
SharePoint online

**Comment by s-KaiNet** [comment]
That's strange, because for Online size limit is [15GB](https://support.office.com/en-us/article/sharepoint-online-limits-8f34ff47-b749-408b-abc0-b605e1f6d498). I don't think you can change it.   
Can you please post exact error message you received?

**Comment by sangaloma** [comment]
Microsoft.SharePoint.Client.InvalidClientQueryExceptionThe request message is too big. The server does not allow messages larger than 262144000 bytes

**Comment by koltyakov** [comment]
Guys, my $0.02, for this case I guess that a custom upload with addChunked might be required as well.

**Comment by sangaloma** [comment]
Is file chunking possible using spsave?

**Comment by s-KaiNet** [comment]
Nope, unfortunately for now chunked upload isn't supported.

**Comment by matcobat** [comment]
I have the same problem here. Do you plan to integrate this feature in spsave ?
@sangaloma , did you find another solution ? Could you share your code if so ?
Thanks to all of you !

**Comment by koltyakov** [comment]
Hi @matcobat, @sangaloma,

Created a sample with chunked upload which can be used as a conditional option when files are large: https://github.com/koltyakov/pnp-upload

The sample is a bit raw and undertested yet I was able to upload large files this way.

**Comment by s-KaiNet** [comment]
I'm closing this one because I don't have plans to add big files support to this library.
