### ISSUE TITLE
How to clear credential cache?

### ISSUE THREAD

**Issue by Perneel** [s-KaiNet/spsave#39]
@s-KaiNet, this might be a silly question:

If I pass 'null' (no authentication) as credentialOptions, the url, username, domain, password, ... are asked in the console which is awesome. Afterward, according to the docs, the credentials are saved 'in a user folder'.

Now, I have mistyped my password, the wrong credentials are stored and spsave keeps using these wrong credentials. How can I clear the stored credentials? 

I searched in the docs of node-sp-auth-config and the default path seems to be "./config/private.json". However, I don't find a private.json on my Windows system. Do you know where I can find this file? I guess that by removing this file, I will be able to re-enter the correct credentials...

> no authentication - do not provide any authentication data at all, like spauth.getAuth(url).then(...). In that case node-sp-auth will ask you for the site url and credentials. You will have to select any of the credential options listed above. Credentials will be stored in a user folder in an encrypted manner.

**Comment by s-KaiNet** [comment]
Hi Steven, when credentials are stored inside user folder, `node-sp-auth` should print path to the file, like ` C:\Users\<user name>\AppData\Roaming\spauth\creds\https___tenant.sharepoint.com_sites_yoursite.json` for windows (json file is generated by replacing slashes in your site url with underscore `_`).     
Can you see anything like this in console?

**Comment by Perneel** [comment]
Excellent, exactly what I was looking for! Thanks for the quick response! :)

PS: yes I see them in the console but it didn't ring a bell, my bad ^^
