### ISSUE TITLE
Multi Factor

### ISSUE THREAD

**Issue by BillySharePoint** [s-KaiNet/spsave#42]
Its not yet compatible with a sharepoint online site that uses multi factor authentication.

**Comment by s-KaiNet** [comment]
Closing as answered in another repository

**Comment by BillySharePoint** [comment]
Thanks for the reply but is there another way if I am not a O365 admin. It seems the link is not visible to users.

**Comment by s-KaiNet** [comment]
Unfortunately no other way. Your admin should enable an option for creating app passwords as described [here](https://support.office.com/en-us/article/set-up-multi-factor-authentication-for-office-365-users-8f0454b2-f51a-4d9c-bcde-2c48e41621c6)
