### ISSUE TITLE
Can I create a new folder without file in a directory?

### ISSUE THREAD

**Issue by anfasci** [s-KaiNet/spsave#49]
Can I create a new folder without file in a directory. I don't need to create new file. My plan is to upload a file After creating a folder. How it possible?
Can you give an example using spsave in nodejs?

**Comment by s-KaiNet** [comment]
This is not possible with spsave.

**Comment by ghost** [comment]
@s-KaiNet  any idea how to implement folder creation

**Comment by s-KaiNet** [comment]
You can use [sp-request](https://github.com/s-KaiNet/sp-request) for that purpose, but it obviously out of the scope for this library.
