### ISSUE TITLE
Where is saved file

### ISSUE THREAD

**Issue by stychu** [s-KaiNet/spsave#50]
I am testing spsave for automation of uploading files to the SP. I was able to save file but I have no idea where it's now.

```
[16:34:07] spsave: Creating folder or full folders hierarchy: 'TESTING'
[16:34:08] spsave: test.txt checked out.
[16:34:09] spsave: test.txt successfully uploaded to 'https://.........sharepoint.com/personal/........../TESTING' and checked in. Checkin type: major
saved
```

Looking through the sahrepoint onedrive webapp interface: files / recent/ shared / recycle bin can't find the created file. Also going on the generated link gives me `NOT FOUND`

**Comment by s-KaiNet** [comment]
Could you post your whole code, please? Don't forget to remove all sensitive information.

**Comment by stychu** [comment]
```
const { spsave } = require("spsave");

const coreOptions = {
  siteUrl: 'https://.......sharepoint.com/personal/.....',
  notification: true,
  checkin: true,
  checkinType: 1
};
const creds = {
  username: process.env.username,
  password: process.env.password,
  // online: true
};

const fileOptions = {
  folder: 'TESTING',
  fileName: 'test.txt',
  fileContent: 'hello world'
};

spsave(coreOptions, creds, fileOptions)
  .then(function(){
    console.log('saved');
  })
  .catch(function(err){
    console.log(err);
  });

```

**Comment by s-KaiNet** [comment]
I guess you're uploading to onedrive. In that case for folder please provide "Documents" value. It will upload a file to the root of your onedrive. "Documents/Testing" will create a subfolder and will upload to that subfolder.

**Comment by stychu** [comment]
Great!! It's working, thanks!

How I would also upload to the shared folder ??

**Comment by s-KaiNet** [comment]
You can upload to a shared folder if you know the exact url of a folder. Otherwise I'm not sure how to do that and have never tried.

**Comment by stychu** [comment]
Great! Will dig it. Thanks for this plugin great work !
