### ISSUE TITLE
Successful upload message

### ISSUE THREAD

**Issue by stychu** [s-KaiNet/spsave#51]
Hello, is there a way to change the default message when the file is successfully uploaded or entirely remove it??
`[18:06:18] spsave: test3.csv successfully uploaded to 'https://..............'`

**Comment by s-KaiNet** [comment]
Hi, `spsave` doesn't support such scenario. You can completely disable logs by using `console.log = function(){}`. However, it will disable logging in other modules.

**Comment by koltyakov** [comment]
I did something like, but can't recall when I needed this:

```typescript
const log = console.log;
console.log = () => {/**/};
await spsave(/* ... */);
console.log = log;
```
