### ISSUE TITLE
Angular 2+ support

### ISSUE THREAD

**Issue by mgordic** [s-KaiNet/spsave#53]
Hi,

Is it possible to use it with Angular 2+?

Thank you
Marko

**Comment by koltyakov** [comment]
Possible. But absolutely separate and not related things. Build pipeline bundles and saves files to disk, upload pipeline saves to SharePoint assets folder. So it can be any framework. And, of course, you got to tweak build pipeline to suite SharePoint-hosting related aspects.

**Comment by s-KaiNet** [comment]
To add to what Andrew @koltyakov commented - you can't use `spsave` directly in angular (i.e. include in browser bundle) because it's intended for nodejs only. However, you can use it as part of your build process (e.g. gulp task, etc.) to upload assets to SharePoint.
