### ISSUE TITLE
Unexpected error started to show up

### ISSUE THREAD

**Issue by stychu** [s-KaiNet/spsave#54]
All was working until now. Can't seem to find the cause of this...

```
[10:06:43] spsave: Error occured:
[10:06:43] spsave: Unexpected close tag
Line: 7
Column: 7
Char: >
```

**Comment by s-KaiNet** [comment]
Which type of authentication do you use?

**Comment by stychu** [comment]
SharePoint online user credentials authentication

username and password

```
const uploadToSharePoint = () => {
  const coreOptions = {
    siteUrl: envs.DESTINATION_URL,
  };

  const creds = {
    username: envs.SP_USERNAME,
    password: envs.SP_PASSWORD,
  };

  const fileOptions = {
    folder: encodeURI(`/Documents/${envs.DESTINATION_FOLDER}`),
    fileName: envs.FILE_NAME,
    fileContent: fs.readFileSync(envs.FILE_NAME),
  };

  return spsave(coreOptions, creds, fileOptions);
};
```

**Comment by s-KaiNet** [comment]
It seems like something changed in your authentication setup - 2FA was added or your organization switched to ADFS. Might it be the case?

**Comment by stychu** [comment]
OKay, I've just checked the account and it seems like I got access denied to the SharePoint... At least I know what's going on ;)

Thanks for the very quick response!

**Comment by stychu** [comment]
I've been trying to dig this the whole day but wasn't successful. The error is very not informative.
From what I've found my company changed from `ADFS SSO to OneLogin` but we were unable to track any problem with login.

I have two accounts where I use spsave and one is working and the other one gives me this error but I am able to login into it and access everything like the I do with the 1st account.

**Comment by s-KaiNet** [comment]
spsave doesn't support any third party login providers, thus the only option for you is to go to [add-in authentication](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint-Online-addin-only-authentication).    
One account works because it uses default microsoft authentication.

**Comment by stychu** [comment]
Fortunately, it works again! :) We changed the domain of the account and it's working. Thanks!
