### ISSUE TITLE
Is it possible to rename the folder in sharepoint ?

### ISSUE THREAD

**Issue by anfasci** [s-KaiNet/spsave#57]
I want to rename one folder which has child folder and files. Is it possible?
My aim is to backup the old file before upload the same folders.

**Comment by koltyakov** [comment]
Yes, it's possible to rename a folder.

**Comment by anfasci** [comment]
how?

**Comment by koltyakov** [comment]
Using SharePoint API, obviously. ;) But this is not the use case of `spsave`.

**Comment by koltyakov** [comment]
Well, ok, trolling aside. To rename a folder you should update `FileLeafRef` property of the folder item. See [PnPjs way](https://github.com/pnp/pnpjs/issues/68). Within gulp task, you can send the corresponding request with PnPjs or a raw one with `sp-request` library

**Comment by anfasci** [comment]
Thanks

**Comment by s-KaiNet** [comment]
Hi @anfasci 
This question is not specific to the library, in future I will close similar issues. Please respect someone else's time. 
Please use special forums like https://sharepoint.stackexchange.com for your specific questions.   
Andrew thank you for your support.
