### ISSUE TITLE
Error: Access Denied

### ISSUE THREAD

**Issue by Casperius88** [s-KaiNet/spsave#60]
I am getting a file from front-end web application, save it to server and then try to upload it to Sharepoint online. Here is the code:

```
            var coreOptions = {
                siteUrl: 'https://*****.sharepoint.com/sites/nav'
            };
            var creds = {
                username: '***@****.gr',
                password: '**********'
            };

            var fileOptions = {
                folder: 'nav/Shared%20Documents/Consignment',
                fileName: req.file.originalname,
                fileContent: fs.readFileSync(`./Temp/${req.file.originalname}`)
            };
            spsave(coreOptions, creds, fileOptions)
            .then(function(){
                console.log('saved');
            })
            .catch(function(err){
                console.log(err);
            });

```

Althouth I am the owner of the site and have full control permission, I am getting this error:

_Access denied. You do not have permission to perform this action or access this resource._

I know that the error is not related to the library, but I wonder if something's wrong with the folder path. Any help would be much appreciated.

**Comment by koltyakov** [comment]
Custom scripts should be enabled on a modern site to allow this. See more https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script
Without it enabled, even admins can't upload scripts.

**Comment by s-KaiNet** [comment]
Since `nav` is your web site, the `folder` should be just `Shared Documents/Consignment`

And yes, please try Andrew's suggestion. 
If nothing works, install [sp-request](https://github.com/s-KaiNet/sp-request) module and check if it returns web information:

```
spr.get('https://*****.sharepoint.com/sites/nav/_api/web')
  .then(response => {
    console.log('web: ' + response.body.d);
  })
  .catch(err =>{
    console.log('Ohhh, something went wrong...');
  });
```

**Comment by Casperius88** [comment]
Thank you both. I modifed folder path and now it works fine :)
