### ISSUE TITLE
[QUESTION] Upload a complete folder to sharepoint ?

### ISSUE THREAD

**Issue by obrassard** [s-KaiNet/spsave#63]
Hello, I hope your fine ! 

I am sorry to open an issue for a question, but I am wondering if there's a way to upload a complete folder to sharepoint with this module ? In other words do we have to upload every files individually or is there a better way to upload the complete directory content ? 

Thanks in advance.

**Comment by koltyakov** [comment]
Hi @obrassard,

SharePoint doesn't have an API for uploading and extracting an archive to process a folder upload in one call. A folder upload looks like getting a list of files from a folder using for example `fs.readdir`, walking through nested folders recursively, and passing required files to `spsave`, awaiting a single upload completed then going to the next one, or managing how many concurrent files are uploaded at the same time.

A sample of the task you're trying to achieve can be found [here](https://github.com/koltyakov/sp-build-tasks/blob/master/src/tasks/sync.ts#L40).

**Comment by obrassard** [comment]
Hi @koltyakov, thanks for your answer ! Couldn't the `glob` file option be use in order to upload several files of a directory ?

**Comment by s-KaiNet** [comment]
Hi Olivier, 

yes, you can try `glob` option to upload all files in a folder, like in [this](https://github.com/s-KaiNet/spsave/blob/master/docs/Recipes.md#save-multiple-files-by-mask-preserve-folder-structure-base-options-is-used) example.

**Comment by obrassard** [comment]
Thanks a lot for your help !
