### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by kymberlyhaugen** [s-KaiNet/spsave#65]
Very sorry if this is a silly mistake but I'm having an issue authenticating and uploading files. I'm omitting my credentials and having it prompt me. I fill in site url, username, domain, and password then get the following error:

`(node:21376) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'statusCode' of undefined
    at C:\Users\[path to my project folder]\node_modules\spsave\lib\src\core\FileSaver.js:95:38
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Here is my code:

`var spsave = require("spsave").spsave;`
`var coreOptions = {`
`    siteUrl: 'https://pathtomysite.com',`
`    checkin: true,`
`    checkinType: 3`
`};`
`var fileOptions = {`
`    folder: 'SiteAssets',`
`    fileName: 'file.txt',`
`    fileContent: 'hello world'`
`};`
`spsave(coreOptions, null, fileOptions)`
`.then(function(){`
`    console.log('saved');`
`})`
`.catch(function(err){`
`    console.log(err);`
`});`

Am I using the wrong authentication type?

**Comment by s-KaiNet** [comment]
Do you use SharePoint Online or on-premises? Could you under `node_modules\spsave\lib\src\core\FileSaver.js` put a console.log(err) at line 95 to see what is the actual error is?

**Comment by kymberlyhaugen** [comment]
We use on-premise.

After adding the console.log(err) I now get this output:

`TypeError: Cannot read property 'body' of undefined
    at C:\Users\[path to my project folder redacted]\node_modules\spsave\lib\src\core\FileSaver.js:199:34
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:17512) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'statusCode' of undefined
    at C:\Users\[path to my project folder redacted]\node_modules\spsave\lib\src\core\FileSaver.js:96:38
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I also see this message in the Problems tab of VS Code:
`No inputs were found in config file 'c:/Users/[path to my project folder redacted]/node_modules/spsave/tsconfig.json'. Specified 'include' paths were '["src/**/*.ts","test/**/*.ts"]' and 'exclude' paths were '["node_modules"]'.`

**Comment by jswiss** [comment]
I am experiencing the same issue, although I am including my credentials and using Sharepoint Online. The strange thing is this is failing for a Typescript project that is otherwise using the exact same code for a regular JS project that successfully saves the file. Have there been any documented issues with the `tsc` compiler interfering with the library?

**Comment by clechner77** [comment]
rerun "npm run config" and that fixes it

**Comment by kymberlyhaugen** [comment]
After moving sites to a new environment the tool worked as expected
