### ISSUE TITLE
[Feature Request] Enable MFA

### ISSUE THREAD

**Issue by marc3218** [s-KaiNet/spsave#75]
# 🚀 Enable MFA [Feature Request]

### Proposal
I'm developing a VS Code extension, which has some company internal features and which should be able upload/download files/folders to/from SharePoint.
spsave & sppull are perfectly suitable for this job as long as user's are not forced to use MFA.
So, username + password are working perfectly fine, but spsave & sppull are not working with MFA.

#### I've researched a bit and here are my results:
It's possible to fetch an accesstoken from the [Microsoft identity platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-overview) via [msal-node](https://www.npmjs.com/package/@azure/msal-node). (Assuming there's an registered app, which is configured properly in portal.azure.com)
With this accesstoken, we are able to fetch the RequestDigest from the SharePoint, in order to upload files.

Sample code:
``` javascript
//Import all libraries
import Axios from "axios";
import * as msal from "@azure/msal-node";
const express = require("express");

//Create Server
const app = express();
const serverPort = 3000;

//msal-config
const config: msal.Configuration = {
    auth: {
        clientId: "YOUR_CLIENT_ID",
        authority: "https://login.microsoftonline.com/common"
    }
};

//Create msal.PublicClientApplication
const clientApplication = new msal.PublicClientApplication(config);

//Neccessary scopes
const scopes = [
    "https://<yourTentant>.sharepoint.com/AllSites.Manage", 
    "https://<yourTentant>.sharepoint.com/AllSites.Read", 
    "https://<yourTentant>.sharepoint.com/AllSites.Write", 
    "https://<yourTentant>.sharepoint.com/MyFiles.Read", 
    "https://<yourTentant>.sharepoint.com/MyFiles.Write"
]

//Config to fetch the AccessToken
const tokenRequestConfig = {
    "redirectUri": "http://localhost:3000/redirect",
    "scopes": scopes
}

//Redirect URI. Is called right after user is logged in successfully
app.get("/redirect", (req: any, res: any) => {
    const tokenRequest = { ...tokenRequestConfig, code: req.query.code };

    clientApplication.acquireTokenByCode(tokenRequest).then(async (response) => {
        console.log("Successfully acquired token using Authorization Code.");
        res.sendStatus(200);

        try {
            //Fetch the digest
            const digestResult: any = await Axios.post(
                "https://<yourTentant>.sharepoint.com/sites/<yourSite>/<yourWeb>/_api/contextinfo",
                "",
                {
                    headers: {
                        "Authorization": "Bearer " + response.accessToken,
                        "accept": "application/json; odata=verbose",
                        "content-type": "application/json; odata=verbose"
                    }
                }
            );

            //Upload
            const uploadResult = await Axios.post(
                "https://<yourTentant>.sharepoint.com/sites/<yourSite>/<yourWeb>/_api/web/folders",
                {
                    "__metadata": { 
                        "type": "SP.Folder" 
                    }, 
                    "ServerRelativeUrl": "Custom/newFolder uploaded from vscode"
                },
                {
                    headers: {
                        "Authorization": "Bearer " + response.accessToken,
                        "X-RequestDigest": digestResult.data.d.GetContextWebInformation.FormDigestValue,       
                        "Accept": "application/json;odata=verbose",
                        "Content-Type": "application/json;odata=verbose",                                                         
                    }
                }
            );

            console.log(uploadResult);
        } catch (error) {
            console.log(error);
        }
        
    }).catch((error) => {
        console.log(error);
        res.status(500).send(error);
    });
});


app.listen(serverPort, () => console.log(`Sample is listening on port ${serverPort}!`));


//Create and call Auth-URL in default browser
try {
  const result = await clientApplication.getAuthCodeUrl({
      scopes: scopes,
      redirectUri: "http://localhost:3000/redirect"
  });

  //Open the AuthCodeURL in the default browser
  vscode.env.openExternal(result);
} catch (error) {
  console.log(error);
}
```

NOTE:
If you need details of the registered app, which is configured properly in portal.azure.com, let me know.

### So, what do I want ?
I think it could be possbile to extend the [IAuthOptions](https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/IAuthOptions.ts) in [sp-request](https://www.npmjs.com/package/node-sp-auth) in a way, that spsave can be called with a bearer token.
The callee (which is me/my VS Code extension) of spsave is responsible to handle everything about the accesstoken (fetch the accesstoken initially, fetch a new accesstoken if expired and so on) and spsave is responsible for the upload and is responsible to fetch the RequestDigest.

What do you think ?
Could you please evaluate my idea ?

### By the way

Would be applicable for sppull as well.
Could be interesting for [spgo](https://www.chrishasz.com/spgo/) as well.

**Comment by s-KaiNet** [comment]
Hi, thanks for the detailed info!

regarding the MFA feature itself - actually, you can use `spsave` with MFA, with the only difference being that you should register an app password as described here - [Create and delete app passwords section](https://support.microsoft.com/en-us/account-billing/manage-app-passwords-for-two-step-verification-d6dc8c6d-4bf7-4851-ad95-6d07799387e9).   

When it comes to extending `spsave` - I'm not planning to add new features to `sp-auth/sp-request/spsave` family simply because I don't use it for more than 3 years now. They are currently in support mode. You can also take a look at the [pnpjs](https://pnp.github.io/pnpjs/) library, which has native nodejs via msal-node auth support and a lot of other cool things.

**Comment by marc3218** [comment]
Hi, thanks for your real quick answer.

Unfortunately, there are multiple reasons for not using app passwords or one-time-passwords.
So, my best bet is to use another library as you suggested.

It's not the place, but I'm here already:
It's pretty sad, because spsave is awesome. The way spsave abstracts the complexity of sharepoint is  just on point. For me, personally, it's the way a library should work - especially in contrast to a fluent library.

So, thank you for creating and sharing the lib(s), even when they are not suitable for me anymore.
